config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  resources :users,only: [:show,:edit,:update,:index]
  root 'home#top'
  get 'home/about'

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :rooms, only: [:create, :show] do
    resources :chats, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord 
	belongs_to :user
	validates :title, presence: true
	validates :body ,presence: true, length: {maximum: 200}
	has_many :favorites
	has_many :book_comments
	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true

end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
  has_many :users, through: :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attachment :profile_image, destroy: false
  has_many :books
  validates :name, presence: true, length: {maximum: 10, minimum: 2}
  validates :introduction, length: {maximum: 50}

  has_many :favorites
  has_many :chats
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
end 

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates  :room_id, uniqueness: { scope: :user_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  private
    #sign in後のredirect先変更
    def after_sign_in_path_for(resource)
      user_path(resource)
    end

    #sign out後のredirect先変更
    def after_sign_out_path_for(resource)
      root_path
    end

    #sin up時の登録情報追加
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profle_image, :email])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name]) # ログイン時にnameを使用
    end
    def correct_user?(user)
      if current_user.nil?
        return false
      else
        user.id.equal?(current_user.id)
      end
    end 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,only: [:create,:edit,:update,:destroy,:index]

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
    screen_user(@book)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book
    else
      @books = Book.all
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_url
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def screen_user(book)
      if book.user.id != current_user.id
        redirect_to books_path
      end
    end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_room, only: [:create, :edit, :update, :destroy]
  before_action :set_chat, only: [:edit, :update, :destroy]

  def create
    if UserRoom.where(user_id: current_user.id, room_id: @room.id)
      @chat = Chat.create(chat_params)
       if @chat.save
        @chat = Chat.new
        gets_user_rooms_all_chats
       end
    else
      flash[:alert] = "メッセージの送信に失敗しました"
    end
  end

  private
  def set_room
    @room = Room.find(params[:chat][:room_id])
  end

  def set_chat
    @chat = Chat.find(params[:id])
  end

  def gets_user_rooms_all_chats
    @chats = @room.chats.includes(:user).order("created_at asc")
    @user_rooms = @room.user_rooms
  end

  def chat_params
    params.require(:chat).permit(:user_id, :message, :room_id).merge(user_id: current_user.id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

  private
  def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to books_path
    when 1
      redirect_to book_path(@book)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @room = Room.create
    @joinCurrentUser = UserRoom.create(user_id: current_user.id, room_id: @room.id)
    @joinUser = UserRoom.create(join_room_params)
    # @first_chat = @room.chats.create(user_id: current_user.id, message: "初めまして！")
    redirect_to room_path(@room.id)
  end

  def show
    @rooms = current_user.rooms.includes(:messages).order("messages.created_at desc")
    @room = Room.find(params[:id])
    if UserRoom.where(user_id: current_user.id, room_id: @room.id).present?
      @chats = @room.chats.includes(:user).order("created_at asc")
      @chat = Chat.new
      @user_rooms = @room.user_rooms
    else
      redirect_back(fallback_location: root_path)
    end
  end


  private
  def join_room_params
    params.require(:user_room).permit(:user_id, :room_id).merge(room_id: @room.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
      if user_signed_in?
        @currentUserUserRoom = UserRoom.where(user_id: current_user.id)
        @userUserRoom = UserRoom.where(user_id: @user.id)
        unless @user.id == current_user.id
          @currentUserUserRoom.each do |cu|
            @userUserRoom.each do |u|
              if cu.room_id == u.room_id
                @haveRoom = true
                @roomId = cu.room_id
              end
            end
          end
          unless @haveRoom
            @room = Room.new
            @user_room = UserRoom.new
          end
        end
      end
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private
    def user_params
       params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def screen_user
      unless params[:id].to_i == current_user.id
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<td>
  <%= link_to(book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
  <% end %>
</td>
<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
<td><%= book.body %></td>
<!-- いいね機能 -->
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
      <%#= fa_icon "heart", text: "#{book.favorites.count}", style: "color: red;" %>
      <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
      <%#= fa_icon "heart-o", text: "#{book.favorites.count}", style: "color: red;" %>
      <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    <% end %>
  <% end %>
</td>
<td>コメント数：<%= book.book_comments.count %></td>

app/views/books/_comment.html.erb
<% book_comments.each do |book_comment| %> <!-- コメント一覧 -->
  <tr>
    <td>
      <%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
        <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy', book_book_comments_path(book_comment), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>

app/views/books/_detail.html.erb
<td><%= link_to(book.user) do %>
  <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
  <%= book.user.name %>
  <% end %>
</td>
<td><%= link_to book.title, book %></td>
<td><%= book.body %></td>
<!-- いいね機能 -->
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    <% end %>
  <% end %>
</td>
<td>コメント数：<%= book.book_comments.count %></td>

<% if book.user == current_user %>
  <td><%= link_to 'Edit', edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
  <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{book.id}"%></td>
<% end %>

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body'%>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12'%>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr class="book_<%= book.id %>">
        <%= render '/books/book', book: book %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h1>Editing Book</h1>
  <!-- <div class='col-md-3 col-md-offset-3'>
  </div> -->
  	<%= render 'layouts/errors', obj: @book %>
		<%= render 'form', book: @book %>
		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
		<%= link_to 'Back', books_path, class: "back" %>
    </div>
    <div class='col-md-3'></div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: current_user %>

    <h2>New book</h2>
    <%= render 'form', book: @book %>
  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'index', books: @books%>
  </div>
</div>

app/views/books/show.html.erb
<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: @book.user %>
    <h2>New book</h2>
    <%= render 'form', book: Book.new %>
  </div>
  

  <div class='col-xs-9'>
		<h2>Book detail</h2>
		<table class='table'>
		  <tr class="book_<%= @book.id %>">
        <%= render 'detail', book: @book %>
      </tr>
    </table>
    <table class="show-tb comment_<%= @book.id %>">
      <%= render 'comment', book_comments: @book.book_comments %>
    </table>
    <div class="comment-form">
      <%= form_with model:[@book, @book_comment], data: {remote: true} do |f| %>
        <%= f.text_area :comment, size: "90x5" %>
        <%= f.submit '送信' %>
      <% end %>
    </div>

  </div>
</div>

app/views/chats/create.js.erb
$("textarea").val("");
$(".chat_<%= @room.id %>").html("<%= j(render 'rooms/chat_area') %>");

app/views/chats/show.html.erb
<div class='row'>
  <div class='col-xs-9'>

    <div class="chat_<%= @room.id %>">
      <%= render 'chat_area' %>
    </div>

  </div>
  <div class='col-xs-3'>

    <div>
      <%= form_with model:[@room, @chat], data: {remote: true} do |f| %>
        <%= f.text_area :message, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
        <%= f.hidden_field :room_id, :value => @room.id %>
        <br>
        <%= f.submit "投稿する" %>
      <% end %>
    </div>

    <%= link_to "ユーザー一覧に戻る", users_path %>

  </div>

app/views/favorites/create.js.erb
if (location.pathname == '/books') {
  $(".book_<%= @book.id %>").html("<%= j(render 'books/book',  book: @book ) %>")
} else {
  $(".book_<%= @book.id %>").html("<%= j(render 'books/detail',  book: @book ) %>")
}

app/views/favorites/destroy.js.erb
if (location.pathname == '/books') {
  $(".book_<%= @book.id %>").html("<%= j(render 'books/book',  book: @book ) %>")
} else {
  $(".book_<%= @book.id %>").html("<%= j(render 'books/detail',  book: @book ) %>")
}

app/views/rooms/_chat_area.html.erb
<div class="left-button">
  <% @user_rooms.each do |ur| %>
    <% current_user == ur.user ? @class = "current_user" : @class = ""  %>
      <% if ur.user != current_user %>
        <h5 class="text-left <%= @class %>" id="<%= @class %>" style="font-size: 30px;" data-id="<%= ur.user.id %>"><%= "#{ur.user.name}" %>さんとのチャット</h5>
      <% end %>
  <% end %>
</div>
<hr>
<div>
  <% if @chats.present? %>
    <% @chats.each do |chat| %>
      <% if chat.user_id == current_user.id %>
        <div class="dm-right">
          <%= attachment_image_tag chat.user, :profile_image, fallback: "no_image.jpg", class:"profile-img-circle", size: "40x40" %>
          <%= chat.user.name %>
          <%= chat.message %><br>
          <%= chat.created_at.strftime("%Y/%m/%d %H:%M") %>
        </div>
      <% else %>
        <div class="dm-left">
          <%= attachment_image_tag chat.user, :profile_image, fallback: "no_image.jpg", class:"profile-img-circle", size: "40x40" %>
          <%= chat.user.name %>
          <%= chat.message %><br>
          <%= chat.created_at.strftime("%Y/%m/%d %H:%M") %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class='row'>
  <div class='col-xs-9'>
    <div class="chat_<%= @room.id %>">
      <%= render 'chat_area' %>
    </div>
  </div>
  <div class='col-xs-3'>
    <div>
      <%= form_with model:[@room, @chat], data: {remote: true} do |f| %>
        <%= f.text_area :message, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
        <%= f.hidden_field :room_id, :value => @room.id %>
        <br>
        <%= f.submit "投稿する" %>
      <% end %>
    </div>
    <%= link_to "ユーザー一覧に戻る", users_path %>
  </div>
</div>

app/views/users/_contact.html.erb
<% if user_signed_in? %>
  <% unless @user.id == current_user.id %>
    <% if @haveRoom == true %>
      <%= link_to "ダイレクトメッセージ", room_path(@roomId) %>
    <% else %>
      <%= form_with model: @room do |f| %>
        <%= fields_for @user_room do |e| %>
          <%= e.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "ダイレクトメッセージ" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
      <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr> 
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>
  <%= render 'layouts/errors', obj: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: current_user %>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Users</h2>

    <%= render 'index',users: @users %>
  </div>

</div>

app/views/users/show.html.erb
<div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: @user,now: ''%>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'books/index',books: @books %>
  </div>
</div>

<%= render 'contact' %>